name: Run api tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.16.x'
      - name: Install tests
        working-directory: ./back_end
        run: yarn && yarn test
